version: '1'
services:
#  web:
#    build: ./nginx
#    ports:
#      - "80:80"
#    depends_on:
#      - frontend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"