#FROM python:3.11
#ENV DjangoHome=/home/app/webapp
#RUN mkdir -p $DjangoHome
#WORKDIR $DjangoHome
#ENV PYTHONDONTWRITEBYTECODE 1
#ENV PYTHONUNBUFFERED 1
#RUN pip install --upgrade pip
#COPY . $DjangoHome
#RUN pip install -r requirements.txt
#EXPOSE 8888
#CMD python manage.py runserver