#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: planning-poker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planning-poker
  template:
    metadata:
      labels:
        app: planning-poker
    spec:
      containers:
        - name: planning-poker-frontend
          image: rubberducks/planning-poker-frontend:TAG
          ports:
            - containerPort: 5173
          imagePullPolicy: Always
        - name: planning-poker-backend
          image: rubberducks/planning-poker-backend:TAG
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
---
#Service
apiVersion: v1
kind: Service
metadata:
  name: planning-poker
spec:
  selector:
    app: planning-poker
  ports:
    - port: 80
      name: tcp-80
      targetPort: 5173
    - port: 8000
      name: tcp-8000
      targetPort: 8000
  type: LoadBalancer
