name: Build, publish and deploy an app to AKS

on:
  push:
    branches: [ "main" ]
    
env:
  AZURE_CONTAINER_REGISTRY: "ppimages"
  CONTAINER_NAME: "planning-poker"
  RESOURCE_GROUP: "pp-rg-2.0"
  CLUSTER_NAME: "pp-cluster"

jobs:

  publish-frontend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: rubberducks/planning-poker-frontend:${{ github.sha }}
          
  publish-backend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: rubberducks/planning-poker-backend:${{ github.sha }}
          
  deploy:
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    needs: [publish-frontend, publish-backend]
    steps:
      - uses: actions/checkout@v3
      
      - name: Replace variables
        run:  cat ./kube/planning-poker.yaml | sed -e s/TAG/${{ github.sha }}/g > deployment.yaml
        shell: bash
      
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.25'

      - name: Get K8s context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          admin: 'false'
          use-kubelogin: 'true'

      - name: Deploys application
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: deployment.yaml
          
